//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deployer2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class container
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string ipaddress { get; set; }
        public string application { get; set; }
        public string owner { get; set; }
    }
}
