//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deployer2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM
    {
        public int Id { get; set; }
        public string vmname { get; set; }
        public int ipaddress { get; set; }
        public int memory { get; set; }
        public string description { get; set; }
        public string os { get; set; }
        public int amountofcpu { get; set; }
        public string owner { get; set; }
    }
}
